config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :cities, :only => :index
    resources :zipcodes

    resources :countries do
      resources :states do
        resources :cities do
        end
      end
    end
  end

  namespace :api, :defaults => { :format => 'json' } do
    resources :zipcodes
  end
end

app/models/spree/city.rb
module Spree
  class City < ActiveRecord::Base
    has_one :zone_member, :as => :zoneable
    has_one :zone, :through => :zone_member
    belongs_to :state
    has_one :country, :through => :state
    validates_presence_of :name
    validates_uniqueness_of :name, :scope => [:state_id]

    attr_accessible :name, :state_id

    def state_and_city
      if state
        state.name + ' - ' + name
      else
        name
      end
    end
  end
end

app/models/spree/country_decorator.rb
module Spree
  Country.class_eval do
    has_many :cities, :through => :states
  end
end

app/models/spree/state_decorator.rb
module Spree
  State.class_eval do
    has_many :cities
  end
end

app/models/spree/tax_rate_decorator.rb
module Spree
  TaxRate.class_eval do
    # Gets the array of TaxRates appropriate for the specified order
    def self.match(order)
      return [] unless order.tax_zone
      [where(:zone_id => order.tax_zone.id).first].compact
    end
  end
end

app/models/spree/zipcode.rb
module Spree
  class Zipcode < ActiveRecord::Base
    has_one :zone_member, :as => :zoneable
    has_one :zone, :through => :zone_member
    validates_presence_of :zipcode
    validates_uniqueness_of :zipcode
    
    belongs_to :state # currently not linked to cities
    attr_accessible :zipcode, :city, :state_id
    
    before_create :set_state_abbr

    private
    
    def set_state_abbr
      self.state_abbr = self.state.abbr
    end
  end
end

app/models/spree/zone_decorator.rb
module Spree
  Zone.class_eval do

    # Returns the matching zone with the highest priority zone type (State, Country, Zone.)
    # Returns nil in the case of no matches.
    def self.match(address)

      return unless matches = self.includes(:zone_members).
        order('zone_members_count', 'created_at').
        select { |zone| zone.include? address }

      ['city', 'state', 'country'].each do |zone_kind|
        if match = matches.detect { |zone| zone_kind == zone.kind }
          return match
        end
      end
      matches.first
    end

    def include?(address)
      return false unless address

      # NOTE: This is complicated by the fact that include? for HMP is broken in Rails 2.1 (so we use awkward index method)
      members.any? do |zone_member|
        case zone_member.zoneable_type
        when "Spree::Zone"
          zone_member.zoneable.include?(address)
        when "Spree::Country"
          zone_member.zoneable_id == address.country_id
        when "Spree::City"
          result = false
          address_city = find_city(address)

          if address_city.present?
            result = (zone_member.zoneable_id == address_city.id)
          end

          result
        when "Spree::State"
          zone_member.zoneable_id == address.state_id
        else
          false
        end
      end
    end

    def country_list
      members.map {|zone_member|
        case zone_member.zoneable_type
        when "Spree::Zone"
          zone_member.zoneable.country_list
        when "Spree::Country"
          zone_member.zoneable
        when "Spree::State"
          zone_member.zoneable.country
        when "Spree::City"
          zone_member.zoneable.country_list
        else
          nil
        end
      }.flatten.compact.uniq
    end

    def find_city(address)
      address_city = nil
      if address.city.present? && address.state.present?
        address_city = City.find(
          :first,
          :conditions => [
            'UPPER(name) = :name and state_id = :state_id',
            { :name => address.city.upcase, :state_id => address.state.id }
        ]
        )
      end
      address_city
    end
  end
end

app/controllers/spree/admin/cities_controller.rb
module Spree
  class Admin::CitiesController < Admin::ResourceController
    belongs_to 'spree/state'
    before_filter :load_data

    def index
      respond_with(@collection) do |format|
        format.html
        format.js  { render :partial => 'city_list.html.erb' }
      end
    end

    protected

    def location_after_save
      admin_country_state_cities_url(@country,@state)
    end

    def collection_url
      admin_country_state_cities_url(@country,@state)
    end

    def collection
      super.order(:name)
    end

    def load_data
      @countries = Country.order(:name)
      @country = Country.find(params[:country_id])
      @states = State.order(:name)
      @state = State.find(params[:state_id])
    end
  end
end

app/controllers/spree/admin/zipcodes_controller.rb
module Spree
  class Admin::ZipcodesController < Admin::ResourceController
    respond_to :html

    before_filter :load_states, :only => [:new, :edit]

    def index
      @search = Spree::Zipcode.order(:zipcode).ransack(params[:q])

      @zipcodes = @search.result.page(params[:page]).
        per(params[:per_page] || Spree::Config[:orders_per_page])
      respond_with(@zipcodes)
    end

    protected

    def load_states
      @states = Spree::State.order(:name)
    end      

    def location_after_save
      admin_zipcodes_url
    end

    def collection_url
      admin_zipcodes_url
    end

    def collection
      super.order(:zipcode)
    end

  end
end

app/controllers/spree/admin/zones_controller_decorator.rb
module Spree
  Admin::ZonesController.class_eval do
    before_filter :load_cities, :except => [:index]
    before_filter :load_zipcodes, :except => [:index]

    protected

    def load_cities
      @cities = City.order(:name)
    end

    def load_zipcodes
      @zipcodes = Zipcode.order(:zipcode)
    end

  end
end

app/controllers/spree/api/zipcodes_controller.rb
module Spree
  module Api
    class ZipcodesController < Spree::Api::BaseController
      def index
        if params[:id]
          @zipcodes = Spree::Zipcode.where(:id => params[:id])
          # render 'spree/api/zipcodes/show' if @zipcode
        else
          # this was horrible, performance-wise
          # @zipcodes = Spree::Zipcode.scoped.ransack(params[:q]).result

          if params[:q][:zipcode_start].present?
            arel_table = Spree::Zipcode.arel_table
            @zipcodes = Spree::Zipcode.where(arel_table[:zipcode].matches("#{params[:q][:zipcode_start]}%"))
          else
            @zipcodes = Spree::Zipcode.scoped
          end
        end

        respond_with(@zipcodes)
      end

      def show
      	@zipcode = Spree::Zipcode.find(params[:id])
      	respond_with(@zipcode.to_arr) # lame, i know.  trying to make the javascript happy
      end

    end
  end
end

app/views/spree/admin/cities/_city_list.html.erb
<table class="index" id='listing_citys'>
  <thead>
    <tr>
      <th><%= t("name") %></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @cities.each do |city|
    	state = city.state
    	country = @state.country
     %>
      <tr id="<%= dom_id city %>">
        <td><%=city.name %></td>
        <td class="actions">
          <%= link_to_with_icon 'edit', t("edit"), edit_admin_country_state_city_url(country, state, city), :class => 'edit' %>
          &nbsp;
          <%= link_to 'Delete', admin_country_state_city_url(country, state, city), :method => 'delete' %>
        </td>
      </tr>
    <% end %>
    <% if @cities.empty? %>
      <tr><td colspan="3"><%= t(:none) %></td></tr>
    <% end %>
  </tbody>
</table>
<div id="new_city"></div>
<p>
  <%= button_link_to t("new_city"), new_admin_country_state_city_url(@country,@state), {
                                                                             :icon => 'add',
                                                                              :id => 'new_city'} %>
</p>

app/views/spree/admin/cities/_form.html.erb
<%= f.field_container :name do %>
  <%= f.label :name, t("name") %><br />
  <%=f.text_field :name %>
<% end %>

app/views/spree/admin/cities/edit.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<h1><%= t("editing_city") %></h1>

<%= render 'spree/shared/error_messages', :target => @state %>

<%= form_for([:admin,@country,@state,@city], :html => { :method => :put }) do |f| %>
  <%= render :partial => "form", :locals => { :f => f } %>
  <%= render :partial => "spree/admin/shared/cities_edit_resource_links" %>
<% end %>

app/views/spree/admin/cities/index.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<h1><%= t("Cities") %></h1>

<p>
  <label for="country"><%= t('country') %></label>
  <select id="country" class='observe_field' data-base-url="<%=admin_states_path(:format => :js)%>?country_id=" data-update="#state-list">
  <%= options_from_collection_for_select(@countries, :id, :name, @country.id) %>
  </select>
</p>

<p>
  <label for="state"><%= t('state') %></label>
  <select id="state" class='observe_field' data-base-url="<%=admin_cities_path(:format => :js)%>?country_id=<%= @country.id %>&state_id=" data-update="#city-list">
  <%= options_from_collection_for_select(@states, :id, :name, @state.id) %>
  </select>
</p>

<%= image_tag "spinner.gif", :plugin=>"spree", :style => "display:none", :id => 'busy_indicator' %>

<div id="city-list">
  <%=render :partial => 'city_list'%>
</div>

app/views/spree/admin/cities/new.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<%= render 'spree/shared/error_messages', :target => @city %>

<%= form_for([:admin,@country,@state,@city]) do |f| %>
  <%= render :partial => "form", :locals => { :f => f } %>
  <%= render :partial => "spree/admin/shared/cities_new_resource_links" %>
<% end %>

app/views/spree/admin/shared/_cities_edit_resource_links.html.erb
<p class="form-buttons">
  <%= button t("update") %>
  <%= t("or") %> <%= link_to t("cancel"), admin_country_state_cities_url %>
</p>

app/views/spree/admin/shared/_cities_new_resource_links.html.erb
<p class="form-buttons">
  <%= button t("actions.create") %>
  <%= t("or") %> <%= link_to t("actions.cancel"), [:admin,@country,@state,@city] %>
</p>

app/views/spree/admin/zipcodes/_form.html.erb
<div data-hook="admin_zipcode_form_fields" class="row">
  <div class="alpha four columns">
    <div data-hook="name" class="field">
      <%= f.label :zipcode, Spree.t(:zipcode) %>
      <%= f.text_field :zipcode, :class => 'fullwidth' %>
    </div>
  </div>
  <div class="four columns">
    <div data-hook="iso_name" class="field">
      <%= f.label :city, Spree.t(:city) %>
      <%= f.text_field :city, :class => 'fullwidth' %>
    </div>
  </div>
  <div class="omega four columns">
    <div data-hook="states_required" class="field checkbox">
      <label>
        <%= f.label :state_id, Spree.t(:state) %>

        <%= f.select :state_id, options_from_collection_for_select(@states, :id, :name, (f.object.state.id rescue nil)) %>
      </label>

    </div>
  </div>
</div>

app/views/spree/admin/zipcodes/edit.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<% content_for :page_title do %>
  <%= Spree.t(:editing_zipcode) %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to Spree.t(:back_to_zipcodes_list), spree.admin_zipcodes_path, :icon => 'icon-arrow-left' %>
  </li>
<% end %>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @zipcode } %>

<%= form_for @zipcode, :url => admin_zipcode_path(@zipcode) do |f| %>
  <fieldset class="no-border-top">
    <%= render :partial => 'form', :locals => { :f => f } %>
    <div data-hook="buttons" class="filter-actions actions">
      <%= button Spree.t('actions.update'), 'icon-refresh' %>
    </div>
  </fieldset>
<% end %>

app/views/spree/admin/zipcodes/index.html.erb
<% content_for :table_filter_title do %>
  <%= Spree.t(:search) %>
<% end %>

<% content_for :table_filter do %>
  <div>
    <%= search_form_for [:admin, @search] do |f| %>
      <div class="four columns">
        <div class="field">
          <%= label_tag nil, Spree.t(:zipcode) %>
          <%= f.text_field :zipcode_start %>
        </div>
      </div>

      <div class="clearfix"></div>

      <div class="actions filter-actions">
        <div>
          <%= button Spree.t(:filter_results), 'icon-search' %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>


<% content_for :page_title do %>
  <%= Spree.t(:listing_zipcodes) %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to Spree.t(:new_zipcode), new_admin_zipcode_url, :icon => 'icon-plus', :id => 'admin_new_zipcode' %>
  </li>
<% end %>


<table class="index" id='listing_zipcodes' data-hook>
  <colgroup>
    <col style="width: 35%" />
    <col style="width: 35%" />
    <col style="width: 20%" />
    <col style="width: 10%" />
  </colgroup>
  <thead>
    <tr data-hook="tax_header">
      <th><%= Spree.t(:zipcode) %></th>
      <th><%= Spree.t(:city) %></th>
      <th><%= Spree.t(:state) %></th>
      <th class="actions"></th>
    </tr>
  </thead>
  <tbody>
    <% @zipcodes.each do |zipcode| %>
      <tr id="<%= spree_dom_id zipcode %>" data-hook="zipcode_row" class="<%= cycle('odd', 'even')%>">
        <td><%= zipcode.zipcode %></td>
        <td><%= zipcode.city %></td>
        <td class="align-center"><%= zipcode.state_abbr %></td>
        <td class="actions">
          <%= link_to_edit_url edit_admin_zipcode_path(zipcode), :title => "admin_edit_#{dom_id(zipcode)}", :no_text => true %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @zipcodes %>

app/views/spree/admin/zipcodes/new.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<% content_for :page_title do %>
  <%= Spree.t(:new_zipcode) %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to Spree.t(:back_to_zipcodes_list), admin_zipcodes_path, :icon => 'icon-arrow-left' %>
  </li>  
<% end %>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @zipcode } %>

<%= form_for @zipcode, :url => collection_url do |f| %>
  <fieldset class="no-border-top">
    <%= render :partial => 'form', :locals => { :f => f } %>
    <div data-hook="buttons" class="filter-actions actions">
      <%= button Spree.t(:create), 'icon-ok' %>
    </div>
  </fieldset>
<% end %>

app/views/spree/admin/zones/_city_member.html.erb
<li>
  <%= f.hidden_field :zoneable_type, :value => "Spree::City" %>
  <%= f.collection_select(:zoneable_id, @cities, :id, :state_and_city, :include_blank => true) %>
  <%= remove_nested f %>
</li>

app/views/spree/admin/zones/_zipcode_member.html.erb
<li class="field">
  <%= f.hidden_field :zoneable_type, :value => "Spree::Zipcode" %>
  <%# f.collection_select(:zoneable_id, @zipcodes, :id, :zipcode, {:include_blank => true}, {:class => 'select2' }) %>
  <%= f.hidden_field :zoneable_id, :class => 'zipcode_select' %>

  <%= remove_nested f %>
</li>

<script>
  $(function() {
    zipcode_autocomplete();
  });
</script>

app/views/spree/shared/_cities_admin_configurations_menu.erb
      <tr>
        <td><%= link_to t("Cities"), spree.admin_country_state_cities_path(Spree::Config[:default_country_id],Spree::State.find(:first, :conditions => {:country_id => Spree::Config[:default_country_id], :abbr => 'CA'})) %></td>
        <td><%= t("cities_description") %></td>
      </tr>